name: Deploy MkDocs site and PDF to GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install system dependencies for PDF generation
        run: |
        
